// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String notify_3648_01FF0100;
String notify_3648_01FF0101;
String notify_3648_01FF0102;
String notify_CC8_01FF0100;
String notify_CC8_01FF0101;
String notify_CC8_01FF0102;
String read_3648_2A24;
String read_3648_2A25;
String read_3648_2A26;
String read_3648_2A29;
String read_CC8_2A24;
String read_CC8_2A25;
String read_CC8_2A26;
String read_CC8_2A29;

void initProperties(){

  ArduinoCloud.addProperty(notify_3648_01FF0100, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notify_3648_01FF0101, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notify_3648_01FF0102, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notify_CC8_01FF0100, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notify_CC8_01FF0101, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(notify_CC8_01FF0102, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_3648_2A24, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_3648_2A25, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_3648_2A26, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_3648_2A29, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_CC8_2A24, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_CC8_2A25, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_CC8_2A26, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(read_CC8_2A29, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
